config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  post 'auth_user' => 'authentication#authenticate_user'
  get 'testa_auth' => 'backoffice/pedidos#teste'
  
  get 'lista_produtos' => 'backoffice/produtos#lista_produtos'
  
  get 'relatorios/form'
  post 'relatorios/gerar_por_periodo'
  
  namespace :backoffice do
  resources :admins
  end
  
  namespace :backoffice do
  namespace :filtrado do
    get 'filtrados/detalhes'
    get 'filtrados/abertos'
    get 'filtrados/fexados'
    end
  end

  namespace :backoffice do
  namespace :filtrado do
     resources :filtrados, only: [ :delathes] do
       get :detalhes, on: :member
     end
  end
end

  namespace :backoffice do
    resources :filtrados
    resources :pedidos, except: [ :destroy] do
      member do
        get :pedido_user
      end
    end
  end

  namespace :backoffice do
    resources :users do
      resources :pedidos do
        collection do
        get :pedido_user
      end
      end
    end
  end
  
  

  namespace :backoffice do
    resources :produtos 
  end
  
  devise_for :admins
  
  

  root 'backoffice#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 
  ROLES = {:full_access => 0, :restricted_access => 1}
  
  enum role: ROLES

  scope :with_full_access, -> { where(role: 0) }
  scope :with_restricted_access, -> { where(role: 1) }

 devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/models/endereco.rb
class Endereco < ActiveRecord::Base
 has_one :user
 accepts_nested_attributes_for :user
end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
  has_many :produtos, through: :pedido_produtos
  has_many :pedido_produtos
  belongs_to :user
  accepts_nested_attributes_for :pedido_produtos
  
  #enum status: { Aberto: 1, Finalizado: 2 }
  
  STATUS = {:Aguardando => 1, :'Em atendimento' => 2, :Finalizado => 3}
  
  enum status: STATUS
  
  scope :waiting, -> { where(status: STATUS[:Aguardando]).or.where(status: STATUS[:'Em atendimento']) }
  
  
end

app/models/pedido_produto.rb
class PedidoProduto < ActiveRecord::Base
  belongs_to :pedido
  belongs_to :produto
  accepts_nested_attributes_for :produto
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  
  belongs_to :produto
  
  has_attached_file :foto, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :foto, content_type: /\Aimage\/.*\z/
  
end

app/models/produto.rb
class Produto < ActiveRecord::Base
  
  belongs_to :tipo_produto 
  
  has_many :pedido_produtos
  has_many :pedidos, through: :pedido_produtos
  has_many :pictures, dependent: :destroy
  
  accepts_nested_attributes_for :tipo_produto
  
end

app/models/tipo_produto.rb
class TipoProduto < ActiveRecord::Base
  has_one :produto
  accepts_nested_attributes_for :produto
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable
  #       :recoverable, :rememberable, :trackable, :validatable
   
  #has_secure_password
  
  has_many :pedidos
  belongs_to :endereco
  
  accepts_nested_attributes_for :endereco
  
 # scope :co_pedido, ->  User.joins(:pedido)
  
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  
  attr_reader :current_user 
  
  protected
  def authenticate_request!
    unless user_id_in_token?
      render json: { errors: ['Not Authenticated'] }, status: :unauthorized
      return
    end
    @current_user = User.find(auth_token[:user_id])
  rescue JWT::VerificationError, JWT::DecodeError
    render json: { errors: ['Not Authenticated'] }, status: :unauthorized
  end

  private
  def http_token
      @http_token ||= if request.headers['Authorization'].present?
        request.headers['Authorization'].split(' ').last
      end
  end

  def auth_token
    @auth_token ||= JsonWebToken.decode(http_token)
  end

  def user_id_in_token?
    http_token && auth_token && auth_token[:user_id].to_i
  end

  
  
end

app/controllers/authentication_controller.rb
  class AuthenticationController < ApplicationController
    
  def authenticate_user
    user = User.find_for_database_authentication(email: params[:email])
    if user.valid_password?(params[:password])
      render json: payload(user)
    else
      render json: {errors: ['Invalid Username/Password']}, status: :unauthorized
    end
  end

  private

  def payload(user)
    return nil unless user and user.id
    {
      auth_token: JsonWebToken.encode({user_id: user.id}),
      user: {id: user.id, email: user.email}
    }
  end
end

app/controllers/backoffice/filtrado/filtrados_controller.rb
class Backoffice::Filtrado::FiltradosController < BackofficeController
  #before_action :authenticate_admin!
  layout "backoffice"
  layout "application", only: :detalhes
  def index  
    
    
  end
  
  def abertos 
    
    @pedido_aguardando = User.joins(:pedidos).where("status = 1 OR status = 2").paginate(:page => params[:page], :per_page => 5)    
    @pedidos_aguardando = Pedido.where("status = 1 OR status = 2").paginate(:page => params[:page], :per_page => 5)
  end
  
  def fexados    
    @pedido_fexado = User.joins(:pedidos).where("status = 3").merge(Pedido.order(updated_at: :desc)).paginate(:page => params[:page], :per_page => 5)
    @pedidos_fexado = Pedido.where("status = 3").order(updated_at: :desc).paginate(:page => params[:page], :per_page => 5)
  end

  def show
    
  end
  
  def detalhes
    
    
    set_pedido
        
  
  end
  
   private
  
    def set_pedido
      @pedido = Pedido.find params[:id]
    end
  
  end
  
  

 

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
 #before_action :authenticate_admin!  
  
  def pundit_user
  	current_admin  	
  end
  
  def index
     @pedido_aguardando = Pedido.where("status = 1")
     @pedido_em_atendimento = Pedido.where("status = 2")
     @pedido_finalizado_no_dia = Pedido.where("status = 3 AND pedidos.updated_at >= ?", Time.zone.now.beginning_of_day)
  end
  
  
  
  private
  
  def user_not_authorized
      flash[:notice] = "You are not authorized to perform this action."
      redirect_to(request.referrer || root_patch)
  end
  
  
end

app/controllers/relatorios_controller.rb
class RelatoriosController < BackofficeController
  
  def form
    
  end

  def gerar_por_periodo
    @data_ini =  DateTime.parse(params[:data_ini]).strftime("%Y-%m-%dT%l:%M:%S%z")
    @data_fin = DateTime.parse(params[:data_fin]).strftime("%Y-%m-%dT%l:%M:%S%z")
    
    
    @pedidos = Pedido.where(created_at: @data_ini..@data_fin, status: 3)
    
    respond_to do |format|
      format.html
      format.pdf do
       render pdf: "file_name_of_your_choice",
               template: "relatorios/gerar_por_periodo.pdf.erb",
               orientation:                    'Portrait', #Landscape
               locals: {:invoice => @invoice}
      end
    end
    
  end
    

  
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
  OptionsForRoles = Struct.new(:id, :description)

	def options_for_roles
		Admin.roles.map do |key, value|
			OptionsForRoles.new(key, value)
	  end	
	end
end

app/helpers/backoffice/filtrado/filtrados_helper.rb
module Backoffice::Filtrado::FiltradosHelper
end

app/helpers/backoffice/pedidos_helper.rb
module Backoffice::PedidosHelper
  OptionsForStatus = Struct.new(:id, :description)

	def options_for_status
		Pedido.statuses.map do |key, value|
			OptionsForStatus.new(key, value)
	  end	
	end
	
	
	def post_date(date)
    # formatting date: Aug, 31 2007 - 9:55PM
    date.strftime("%d/%m/%Y - %H:%M")
  end
	
end

app/helpers/backoffice/produtos_helper.rb
module Backoffice::ProdutosHelper
end

app/helpers/backoffice/users_helper.rb
module Backoffice::UsersHelper
end

app/helpers/backoffice_helper.rb
module BackofficeHelper
end

app/helpers/relatorios_helper.rb
module RelatoriosHelper
end

app/views/backoffice/filtrado/filtrados/abertos.html.erb
<div id="page-wrapper">
  <div class="row">
    <!--   <div class="col-lg-12">
          <h1 class="page-header">Pedidos</h1>
      </div>
      <!-- /.col-lg-12 -->
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2>Listando Pedidos</h2>
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <div class="apple_pagination">
          <%= will_paginate @pedidos_aguardando, :container => false %>
        </div>
        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover">
            <thead>
              <tr>
                <th>Pedido</th>
                <th>Status</th>
                <th>Data do pedido </th>
                <th>Cliente </th>
                <th> </th>
              </tr>
            </thead>
            <tbody>
              <% @pedidos_aguardando.each do |pedido| %>
                 <tr>
                  <td>
                    <%= link_to pedido.id, detalhes_backoffice_filtrado_filtrado_path(pedido), target: '_blank' %>
                  </td>
                  <td>
                    <%= pedido.status%>
                  </td>
                  <td>
                    <%= post_date pedido.created_at%>
                  </td>
                  <td>
                    <%= pedido.user.nome %>
                  </td>
                  <td width="50px">
                    <%= link_to edit_backoffice_pedido_path(pedido), class:"btn btn-primary btn-circle" do %>
                      <i class="fa fa-edit"></i>
                      <% end %>
                  </td>
                </tr>        
              <% end %>
            </tbody>
          </table>
        </div>
        <!-- /.table-responsive -->
      </div>
      <!-- /.panel-body -->
    </div>
  </div>
</div>

app/views/backoffice/filtrado/filtrados/detalhes.html.erb
<div class="panel-body">
  <div class='container-fluid'>
    <div class='panel panel-default'>
      <div class="panel-body">

        <div class="col-xs-6">
          <div class="col-xs-6">
            <p><b>Pedido:</b>
              <%= @pedido.id%>
            </p>
            <p><b>Nome Cliente:</b>
              <%= @pedido.user.nome%>
            </p>
            <p><b>Telefone</b>:
              <%= @pedido.user.tel_cel%>
            </p>
          </div>
          <div class="col-xs-6">
            <p><b>Endereço</b></p>
            <p><b>Rua:</b>
              <%= @pedido.user.endereco.rua %>
                <%= @pedido.user.endereco.complemento %>
            </p>
            <p><b>Cidade:</b>
              <%= @pedido.user.endereco.cidade %>
            </p>
            <p><b>Cep:</b>
              <%= @pedido.user.endereco.cep %>
            </p>
            </p>
          </div>
        </div>
        <div class="col-xs-6 ">
          <div class="pull-right ">
            <h1>Preço Total</h1>
            <h3>
              R$<%total = 0 %>
              <% @pedido.pedido_produtos.each do |a|%>
                <% total += a.contador * a.produto.valor_venda %>
              <% end %>
              <%=number_with_precision(total, precision: 2) %>
            </h3>
          </div>
        </div>
      </div>
      <div class="panel-body">

        <table class='table table-bordered table-striped'>
          <tr>
            <th>Código</th>
            <th>Produto</th>
            <th>Quantidade</th>
            <th>Valor Unitário</th>
            <th>Valor Total</th>
          </tr>
          <tbody>
            <% @pedido.pedido_produtos.each do |cada| %>
              <tr>
                <td>
                  <%= cada.produto.id %>
                </td>
                <td>
                  <%= cada.produto.produto %>
                </td>
                <td>
                  <%= cada.contador %>
                </td>
                <td>
                  R$
                  <%= number_with_precision(cada.produto.valor_venda, precision: 2) %>
                </td>
                <td>
                  <% v_total = cada.contador * cada.produto.valor_venda %>
                    R$
                    <%= number_with_precision(v_total, precision: 2) %>
                </td>
              </tr>
              <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

app/views/backoffice/filtrado/filtrados/fexados.html.erb
<div id="page-wrapper">
  <div class="row">
    <!--   <div class="col-lg-12">
          <h1 class="page-header">Pedidos</h1>
      </div>
      <!-- /.col-lg-12 -->
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2>Listando Pedidos</h2>
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <div class="apple_pagination">
          <%= will_paginate @pedidos_fexado, :container => false %>
        </div>
        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover">
            <thead>
              <tr>
                <th>Pedido</th>
                <th>Status</th>
                <th>Data da finalização </th>
                <th>Cliente </th>
                <th> </th>
              </tr>
            </thead>
            <tbody>
              <% unless @pedidos_fexado.empty? %>
              <% @pedidos_fexado.each do |pedido| %>
                <tr>
                  <td>
                    <%= link_to pedido.id, detalhes_backoffice_filtrado_filtrado_path(pedido), target: '_blank' %>                  
                  </td>
                  
                  <td>
                    
                    <%=pedido.status%>
             
                  </td>
                  <td>
                    <%= post_date(pedido.updated_at)%>
                  </td>
                    
                  <td>
                    <%= pedido.user.nome %>
                  </td>

                  <td width="50px">
                    <%= link_to edit_backoffice_pedido_path(pedido), class:"btn btn-primary btn-circle" do %>
                      <i class="fa fa-edit"></i>
                      <% end %>
                  </td>
                </tr>
                <% end %>
               <% end %>
            </tbody>


          </table>
        </div>
        <!-- /.table-responsive -->
      </div>
      <!-- /.panel-body -->
    </div>
  </div>
</div>

app/views/backoffice/filtrado/filtrados/index.html.erb
<h1>Backoffice::Filtrado::Filtrados#index</h1>
<p>Find me in app/views/backoffice/filtrado/filtrados/index.html.erb</p>