config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  post 'auth_user' => 'authentication#authenticate_user'
  get 'testa_auth' => 'backoffice/pedidos#teste'
  
  get 'lista_produtos' => 'backoffice/produtos#lista_produtos'
  
  get 'relatorios/form'
  post 'relatorios/gerar_por_periodo'
  
  namespace :backoffice do
  resources :admins
  end
  
  namespace :backoffice do
  namespace :filtrado do
    get 'filtrados/detalhes'
    get 'filtrados/abertos'
    get 'filtrados/fexados'
    end
  end

  namespace :backoffice do
  namespace :filtrado do
     resources :filtrados, only: [ :delathes] do
       get :detalhes, on: :member
     end
  end
end

  namespace :backoffice do
    resources :filtrados
    resources :pedidos, except: [ :destroy] do
      member do
        get :pedido_user
      end
    end
  end

  namespace :backoffice do
    resources :users do
      resources :pedidos do
        collection do
        get :pedido_user
      end
      end
    end
  end
  
  

  namespace :backoffice do
    resources :produtos 
  end
  
  devise_for :admins
  
  

  root 'backoffice#index'

end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only: [:edit, :update, :destroy]
  after_action :verify_authorized, only: [:new, :edit, :destroy]
  after_action :verify_policy_scoped, only: :index
  
  def index
    #@admins = Admin.all
    @admins = policy_scope(Admin)
  end
  
  def new
    @admin = Admin.new
    authorize @admin
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to root_path, notice: "O administrador (#{@admin.email}) foi cadastrado com sucesso!"
    else 
      render :new
    end
  end
  
   def edit
    authorize @admin
    end

  def update
    if @admin.update(params_admin)      
      redirect_to backoffice_admins_path, notice: "O administrador (#{@admin.email}) foi cadastrado com sucesso!"
    else 
      render :edit
    end
  end
  
  def destroy
    authorize @admin
   admin_email = @admin.email
    if @admin.destroy
      redirect_to backoffice_admins_path, notice: "O administrador (#{admin_email}) foi excluido com sucesso!"
    else
      render :index
    end

    
  end
  
  private

    def set_admin
      @admin = Admin.find(params[:id])
    end

    def params_admin
       passwd = params[:admin][:password]
       passwd_confirmation = params[:admin][:password_confirmation]

    if passwd.blank? && passwd_confirmation.blank?
      params[:admin].except!(:password, :password_confirmation)
    end

      params.require(:admin).permit(:name, :email, :password, :password_confirmation, :role)
    end
  
  
end

app/controllers/backoffice/filtrado/filtrados_controller.rb
class Backoffice::Filtrado::FiltradosController < BackofficeController
  #before_action :authenticate_admin!
  layout "backoffice"
  layout "application", only: :detalhes
  def index  
    
    
  end
  
  def abertos 
    
    @pedido_aguardando = User.joins(:pedidos).where("status = 1 OR status = 2").paginate(:page => params[:page], :per_page => 5)    
    @pedidos_aguardando = Pedido.where("status = 1 OR status = 2").paginate(:page => params[:page], :per_page => 5)
  end
  
  def fexados    
    @pedido_fexado = User.joins(:pedidos).where("status = 3").merge(Pedido.order(updated_at: :desc)).paginate(:page => params[:page], :per_page => 5)
    @pedidos_fexado = Pedido.where("status = 3").order(updated_at: :desc).paginate(:page => params[:page], :per_page => 5)
  end

  def show
    
  end
  
  def detalhes
    
    
    set_pedido
        
  
  end
  
   private
  
    def set_pedido
      @pedido = Pedido.find params[:id]
    end
  
  end
  
  

 

app/controllers/backoffice/pedidos_controller.rb
class Backoffice::PedidosController < BackofficeController
  before_action :set_pedido, only: [:edit, :update, :show]
  before_action :set_user, only: [:pedido_user]
  
  before_filter :authenticate_request!, only: [:teste]
  
  layout "backoffice", except: [:teste]
  
   
  
  def teste
   @pedidoss = Pedido.all 
     respond_to do |format|
        format.json { render json: @pedidoss  }
        format.html{render 'testa_auth/teste'}
     end
  end
  
  def index   
    @pedidos = Pedido.all
    render json: {pedidos: @pedidos.as_json(include: {pedido_produtos: {include: {produto: {only: [:valor_venda,:produto]}}, except: [:updated_at, :created_at]}})}
     
  end
  
  def pedido_user
    render json: {pedidos: @user}
    
  end
  
  def edit
    
  end
  
  def show
    render json: @pedido, include: {pedido_produtos: {include: {produto: {only: [:valor_pago,:produto]}}, except: [:updated_at, :created_at]}}
  end
  

  def update   
    respond_to do |format|
      if @pedido.update(params_pedido)
        #Backoffice::PedidoMailer.atualiza_pedido(@pedido.user).deliver
        format.json { render json: @pedido, status: :ok }    
        format.html { redirect_to backoffice_filtrado_filtrados_abertos_path, notice: "O pedido foi alterado com sucesso"}
      else 
        format.html { render :edit }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end
  
  
  def create
    @pedido = Pedido.new(params_pedido)    
    respond_to do |format|
      if @pedido.save!
        format.json { render json: @pedido, include: {pedido_produtos: {include: {produto: {only: [:valor_pago,:produto]}}}}}
      else
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end
    
  
  private
  
    def set_pedido
      @pedido = Pedido.find params[:id]
    end
    
  def set_user
    @usersd = User.joins(:pedidos).all
    @user = @usersd.select("pedidos.*").where(:id => params[:id]).all
   # @id = params[:id]
   # @sser = Pedido.all
   # @sser = @sser.where(:user_id => @id).all
  end
  
  
  def params_pedido
      params.require(:pedido).permit(
        :status, 
        :numero_nf,                     
        :total,
        :user_id,
        pedido_produtos_attributes: [
          :contador,
          :tipo_medida,
          :pedido_id,
          :produto_id,
          produtos_attributes: [
            :valor_pago,
            :produto
            ]
        ]                
      )    
    end
    
   
end

app/controllers/backoffice/produtos_controller.rb
class Backoffice::ProdutosController < BackofficeController
  require 'socket'
  
  
  
  before_action :set_produto, only: [:show, :edit]

  
  def index
    @produtos = Produto.all.paginate(:page => params[:page], :per_page => 5)
  
    respond_to do |format|      
      format.html { render "index"}    
    end
    
  end
  
  def new
    @produto = Produto.new
  end
  
  def lista_produtos
    @lista = Produto.all
 
  end
  
  def show
    render json: @produto, except: [:created_at, :updated_at, :valor_pago]
  end
  
  
  def create
    @produto = Produto.new(params_prod)
    if @produto.save
       if params[:images]
        #===== The magic is here ;)
        params[:images].each { |image|
          @produto.pictures.create(foto: image)
        }
      end
      redirect_to backoffice_produtos_path, notice: "O produto (#{@produto.produto}) foi cadastrado com sucesso!"
    else 
      render :new
    end
  end
  
  def edit
  
  end

  def update
    if @produto.update(params_prod)      
      redirect_to :index, notice: "O produto (#{@produto.produto}) foi cadastrado com sucesso!"
    else 
      render :edit
    end
  end
  
  
  
  private
  
  def original_url
    base_url + original_fullpath
  end
    def set_produto
      @produto = Produto.find params[:id]
    end 
    
    def params_prod   
      params.require(:produto).permit(:produto, 
        :desc_produto, 
        :qtd_estoque, 
        :valor_pago, 
        :valor_venda, 
        :tipo_produto_id,
        :foto,
        tipo_produto_attributes: [
          :id,
          :nome_tipo
          ])
    end

end

app/controllers/backoffice/users_controller.rb
class Backoffice::UsersController < BackofficeController    
  before_action :set_user, only: [:edit, :update]
    
  
  def index
    @users = User.all.paginate(:page => params[:page], :per_page => 5)
    respond_to do |format|
      format.json { render json: @users }
      format.html      
    end
  end
  
  def edit
  end
  
  def update   
    respond_to do |format|
      if @user.update(params_user)
        format.json { render json: @user, status: :ok }    
      else 
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def create
    @user = User.new(params_user)    
    respond_to do |format|
      if @user.save!
        format.json { render json: @user, include: :endereco}
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  
  
  private
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def params_user
       passwd = params[:user][:password]
       passwd_confirmation = params[:user][:password_confirmation]

    if passwd.blank? && passwd_confirmation.blank?
      params[:user].except!(:password, :password_confirmation)
    end

      params.require(:user).permit(:nome, 
        :email, 
        :password, 
        :password_confirmation, 
        :cpf, 
        :tel_fixo, 
        :tel_cel,
        :endereco_id,
        endereco_attributes:[
          :rua,
          :bairro,
          :cidade,
          :uf,
          :cep,
          :referencia,
          :numero,
          :complemento          
          ]
        )
    end  
  
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
 #before_action :authenticate_admin!  
  
  def pundit_user
  	current_admin  	
  end
  
  def index
     @pedido_aguardando = Pedido.where("status = 1")
     @pedido_em_atendimento = Pedido.where("status = 2")
     @pedido_finalizado_no_dia = Pedido.where("status = 3 AND pedidos.updated_at >= ?", Time.zone.now.beginning_of_day)
  end
  
  
  
  private
  
  def user_not_authorized
      flash[:notice] = "You are not authorized to perform this action."
      redirect_to(request.referrer || root_patch)
  end
  
  
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
  OptionsForRoles = Struct.new(:id, :description)

	def options_for_roles
		Admin.roles.map do |key, value|
			OptionsForRoles.new(key, value)
	  end	
	end
end

app/helpers/backoffice/filtrado/filtrados_helper.rb
module Backoffice::Filtrado::FiltradosHelper
end

app/helpers/backoffice/pedidos_helper.rb
module Backoffice::PedidosHelper
  OptionsForStatus = Struct.new(:id, :description)

	def options_for_status
		Pedido.statuses.map do |key, value|
			OptionsForStatus.new(key, value)
	  end	
	end
	
	
	def post_date(date)
    # formatting date: Aug, 31 2007 - 9:55PM
    date.strftime("%d/%m/%Y - %H:%M")
  end
	
end

app/helpers/backoffice/produtos_helper.rb
module Backoffice::ProdutosHelper
end

app/helpers/backoffice/users_helper.rb
module Backoffice::UsersHelper
end

app/helpers/backoffice_helper.rb
module BackofficeHelper
end

app/views/backoffice/index.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Painel de controle</h1>
      </div>
      <div class="panel-body">


        <div class="col-lg-3 col-md-6">
          <div class="panel panel-red">
            <div class="panel-heading">
              <div class="row">
                <div class="col-xs-3">
                  <i class="fa fa-shopping-cart fa-5x"></i>
                </div>
                <div class="col-xs-9 text-right">
                  <div class="huge">
                    <%= @pedido_aguardando.count %>
                  </div>
                  <div>Pedidos Abertos!</div>
                </div>
              </div>
            </div>
            <%= link_to  backoffice_filtrado_filtrados_abertos_path do %>
              <div class="panel-footer">
                <span class="pull-left">View Details</span>
                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                <div class="clearfix"></div>
              </div>
              <% end %>
          </div>
        </div>

        <div class="col-lg-3 col-md-6">
          <div class="panel panel-yellow">
            <div class="panel-heading">
              <div class="row">
                <div class="col-xs-3">
                  <i class="fa fa-rocket fa-5x"></i>
                </div>
                <div class="col-xs-9 text-right">
                  <div class="huge">
                    <%= @pedido_em_atendimento.count %>
                  </div>
                  <div>Em Atendimento!</div>
                </div>
              </div>
            </div>
            <%= link_to  backoffice_filtrado_filtrados_abertos_path do %>
              <div class="panel-footer">
                <span class="pull-left">View Details</span>
                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                <div class="clearfix"></div>
              </div>
              <% end %>
          </div>
        </div>

        <div class="col-lg-3 col-md-6">
          <div class="panel panel-primary">
            <div class="panel-heading">
              <div class="row">
                <div class="col-xs-3">
                  <i class="fa fa-road fa-5x"></i>
                </div>
                <div class="col-xs-9 text-right">
                  <div class="huge">
                    <%= @pedido_finalizado_no_dia.count %>
                  </div>
                  <div>Finalizados no dia!</div>
                </div>
              </div>
            </div>
            <%= link_to  backoffice_filtrado_filtrados_fexados_path do %>
              <div class="panel-footer">
                <span class="pull-left">View Details</span>
                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                <div class="clearfix"></div>
              </div>
              <% end %>
                </a>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>